[package]
name = "rc-zip-sync"
version = "3.0.0"
description = "Synchronous zip reading on top of rc-zip"
repository = "https://github.com/fasterthanlime/rc-zip"
license = "Apache-2.0 or MIT"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2021"
readme = "README.md"

keywords = ["zip", "unzip"]
categories = ["compression"]

[lib]
name = "rc_zip_sync"
path = "src/lib.rs"

[[example]]
name = "jean"
path = "examples/jean.rs"

[dependencies]
positioned-io = { version = "0.3.3", optional = true }
rc-zip = { version = "2.0.1", path = "../rc-zip" }
oval = "2.0.0"
tracing = "0.1.40"

[features]
default = ["file", "deflate"]
file = ["positioned-io"]
deflate = ["rc-zip/deflate"]
deflate64 = ["rc-zip/deflate64"]
lzma = ["rc-zip/lzma"]
bzip2 = ["rc-zip/bzip2"]
zstd = ["rc-zip/zstd"]

[dev-dependencies]
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
humansize = "2.1.3"
indicatif = "0.17.7"
test-log = { version = "0.2.14", default-features = false, features = ["tracing-subscriber", "trace"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
rc-zip = { version = "2.0.1", path = "../rc-zip", features = ["corpus"] }
cfg-if = "1.0.0"
